-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 13:38:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(2) NULL,
  `Country` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;

INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('David', 'King', '694.588.2085x62938', '13668 Holt Road', 'East Susan', 'RI', 'USA', '94717');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Debra', 'Chavez', '001-680-237-3396x7867', '17974 Bennett Park Suite 871', 'New Curtis', 'NH', 'USA', '84602');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Christian', 'Dunn', '589.909.2267x101', '289 April Path', 'Carrollburgh', 'NE', 'USA', '61549');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Donald', 'Mitchell', '+1-168-256-8852', '5530 Angela Forest', 'Andreashire', 'AZ', 'USA', '39973');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Mariah', 'Campbell', '(402)570-2268x688', '089 Arnold Road Suite 832', 'East Lanceton', 'MN', 'USA', '39939');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jason', 'Schwartz', '668-361-8925x5979', '747 Wall Viaduct Suite 381', 'South Sheila', 'SD', 'USA', '14629');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('John', 'Valentine', '666-757-5637', '10384 Williams Lights Suite 462', 'Rileyfort', 'NM', 'USA', '28032');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Desiree', 'Tucker', '182.434.6695', '7308 Holly Ports Suite 943', 'Sarahborough', 'AZ', 'USA', '01121');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Adam', 'Villarreal', '(106)982-1731x524', '49996 Rodriguez Junction', 'South Debbie', 'MD', 'USA', '13430');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Michelle', 'Greene', '864.999.4071x14683', '869 Silva Highway Apt. 244', 'North Andrew', 'SD', 'USA', '62884');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('William', 'Smith', '788-828-7620', '84431 Roger Isle', 'South Jeremyfurt', 'MD', 'USA', '95662');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Amanda', 'Salinas', '(071)430-9986', '9086 Mcdonald Plaza', 'West Laurenville', 'DC', 'USA', '58731');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Aaron', 'Ferguson', '(857)307-1912x9880', '58002 Jackson Plaza', 'Mcgeemouth', 'IN', 'USA', '33806');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Christy', 'Rose', '3815955306', '3573 Rebecca Wells Apt. 584', 'New Lawrence', 'ID', 'USA', '18248');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Ethan', 'Fuentes', '415.162.1103', '880 Beth Cape', 'Danielton', 'NY', 'USA', '20621');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Crystal', 'Lester', '636-843-4415x326', '852 Mcbride Summit', 'Simonhaven', 'OH', 'USA', '79268');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('James', 'Daniels', '195.603.5629x6135', '8569 Davis Wells Suite 231', 'Ramirezville', 'HI', 'USA', '39923');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Lisa', 'Reid', '866-806-7616', '4599 Cruz Streets Suite 194', 'South Anthonyborough', 'MI', 'USA', '37872');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jimmy', 'Murphy', '525-153-0668x25785', '747 Amber Loaf Suite 197', 'Leeside', 'FL', 'USA', '89030');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Christian', 'Larson', '608-772-1781', '827 Kathleen Forge', 'Lake Daniel', 'DC', 'USA', '80335');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Brenda', 'Erickson', '001-793-641-1025x1130', '5372 Valerie Lake', 'Bowmanburgh', 'TX', 'USA', '98883');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Michael', 'Hodge', '(006)736-9846x995', '11376 Smith Mountains Apt. 682', 'Port Patrick', 'AZ', 'USA', '78134');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Misty', 'Jordan', '3064095208', '2408 Dominique Trace', 'Lake Raymondborough', 'NJ', 'USA', '80815');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Matthew', 'Brown', '515.266.5340x0839', '56081 Randy Avenue Apt. 011', 'North Christineburgh', 'OH', 'USA', '79619');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jennifer', 'Wheeler', '662-395-4257x74454', '440 Shane Haven Apt. 468', 'East Alyssa', 'UT', 'USA', '00659');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Lori', 'Knight', '925-490-8766x97818', '105 John Fields Suite 008', 'Lake Wendyshire', 'KS', 'USA', '53078');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Alexander', 'Adams', '068-960-6249x521', '58788 Butler Road', 'Jacksonmouth', 'NM', 'USA', '33748');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('John', 'Johnson', '0885095180', '4447 Wall Lakes Apt. 823', 'Aprilport', 'LA', 'USA', '79298');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Eddie', 'Brock', '742.352.1902', '86993 Odom River Apt. 805', 'Josephchester', 'KS', 'USA', '43818');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Nicole', 'Oconnor', '+1-710-222-7750x010', '7525 Lauren Fields Apt. 465', 'New Luisborough', 'NH', 'USA', '97774');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Shelby', 'Kelley', '707-671-1988', '280 Julia Light Suite 711', 'Lake Codyville', 'NY', 'USA', '23022');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Eddie', 'Collier', '948-993-2036x707', '894 Smith Plain Apt. 039', 'East Sarahmouth', 'DE', 'USA', '53581');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Dominique', 'Kennedy', '+1-097-188-0223x09550', '1300 Jose Points Suite 329', 'Michaelport', 'KS', 'USA', '98437');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Kristina', 'Mcdaniel', '8912966238', '80568 Carr Hollow Suite 627', 'Danielleshire', 'PA', 'USA', '69830');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Eric', 'Parker', '971-117-5914', '168 Brown Lodge Apt. 523', 'Lake Christopher', 'ME', 'USA', '19936');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('John', 'Farmer', '001-676-227-7270x684', '775 Melissa Ports Suite 192', 'North Kenneth', 'RI', 'USA', '94055');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Wendy', 'Anderson', '001-702-609-0967x2470', '36594 Kline Trace', 'Toniport', 'SD', 'USA', '65301');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Kylie', 'Delgado', '2545765523', '595 Jennifer Parks Suite 638', 'Juliebury', 'WV', 'USA', '92267');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Megan', 'Morgan', '(329)162-9551', '10602 Victoria Grove', 'Port Lisa', 'VT', 'USA', '60609');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Natalie', 'Smith', '+1-094-099-8266x66061', '13625 Mary Shores', 'Landryberg', 'WI', 'USA', '36228');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Shawn', 'Rodriguez', '849.780.4530x645', '468 Johnny Islands', 'New Jeffreyfurt', 'IN', 'USA', '29671');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Andrew', 'Miller', '925-105-9744x19746', '650 Heidi Stravenue', 'Port Patrickburgh', 'RI', 'USA', '91646');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Matthew', 'Evans', '001-917-568-9603', '94057 Richard Island', 'Schmidtside', 'FL', 'USA', '37633');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('William', 'Jackson', '+1-274-174-3496', '521 Julie Motorway Apt. 950', 'Alvinshire', 'NH', 'USA', '07921');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Matthew', 'Ingram', '931.804.2313', '937 Austin Hills', 'Lake Donald', 'AK', 'USA', '21705');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Michael', 'Larson', '+1-706-320-2635x2983', '346 Robin Loaf', 'South Julie', 'NH', 'USA', '62444');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('John', 'Kelley', '(745)212-4820x30154', '50134 Brandy Points', 'Jamesstad', 'WI', 'USA', '41476');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Amy', 'Thomas', '(388)761-8248', '831 Decker Skyway', 'Thomasville', 'ID', 'USA', '44509');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Karen', 'Hart', '(016)964-7324x32840', '66394 Hansen Valley Suite 882', 'Thomasstad', 'MA', 'USA', '75898');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Nina', 'Carlson', '+1-208-482-0236x664', '7648 Williams Trafficway Suite 677', 'South Ariana', 'NJ', 'USA', '34618');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Mary', 'Henry', '708.218.2206x4366', '11195 Julie Centers', 'West Jennamouth', 'OH', 'USA', '55171');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Stephanie', 'Stephens', '+1-953-801-0641x45999', '2788 Simon Knoll', 'West Cody', 'CT', 'USA', '64368');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('William', 'Wallace', '235.588.9532x908', '3427 Kelsey Roads', 'South Christopher', 'CA', 'USA', '80562');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Pamela', 'Larson', '529.520.3453x7079', '665 Diana Skyway Suite 538', 'South Ronald', 'MA', 'USA', '83444');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jillian', 'Reynolds', '144.119.3855x6305', '52793 Christina Alley Apt. 364', 'Martinezshire', 'DE', 'USA', '49636');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Robert', 'Crosby', '+1-856-749-0938', '46418 Cabrera Burg', 'East Steven', 'SD', 'USA', '25456');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Anthony', 'Garcia', '771-560-3362', '40978 Jones Light', 'Parkerchester', 'CT', 'USA', '58065');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Lisa', 'Cooke', '(872)296-5269x833', '20860 Jones Point Suite 599', 'New Carolview', 'CA', 'USA', '98393');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Shannon', 'Baker', '096-949-1199x8024', '55918 Jordan Extension', 'Jamesport', 'MS', 'USA', '38361');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Gregory', 'Jackson', '795.755.0727', '30772 Karen Club', 'Rossburgh', 'ID', 'USA', '01013');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Kevin', 'Hunt', '088.941.1022x161', '6083 Sherry Summit Suite 477', 'North Teresa', 'IN', 'USA', '61616');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Megan', 'Jones', '+1-436-970-5879', '67232 Rowe Land', 'West Elizabethborough', 'DC', 'USA', '47652');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Kristen', 'Smith', '001-864-591-2873x6479', '98244 Williams Vista Apt. 868', 'Westberg', 'ND', 'USA', '36108');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Elizabeth', 'Burns', '6364306615', '189 Michael Estate Apt. 875', 'New Rodneyberg', 'ME', 'USA', '79669');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Roger', 'Gomez', '792-739-7906x52305', '984 Gardner Turnpike Suite 285', 'East Jonathonmouth', 'MS', 'USA', '71836');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('April', 'Daniels', '0481058695', '954 Justin Fall Suite 443', 'Jessicafurt', 'IL', 'USA', '29974');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Cynthia', 'Dalton', '720-918-4263x8090', '165 David Ports Suite 361', 'South Jennifer', 'DC', 'USA', '08760');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Joshua', 'Nelson', '019-573-4607', '38646 Lauren Flats Apt. 122', 'Lake Sheriburgh', 'UT', 'USA', '44170');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Thomas', 'Tucker', '7503775711', '39752 Lewis Well Suite 639', 'Port Seanfurt', 'NH', 'USA', '22689');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Angela', 'Mccarthy', '052.522.4472x6492', '5046 Kendra Burg Apt. 938', 'Tranborough', 'AR', 'USA', '11941');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jennifer', 'Sawyer', '(858)249-8365', '9920 Karen Views Apt. 176', 'Barbarafurt', 'MA', 'USA', '18455');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Eric', 'Rivers', '001-364-295-5188x569', '0918 Russell Estate Apt. 257', 'Shelleyville', 'LA', 'USA', '48808');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Debra', 'Meza', '897.028.8679', '5090 Jared Islands Suite 016', 'North Debraborough', 'IA', 'USA', '38666');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Kimberly', 'Davis', '572-747-7003', '395 Krista Lake Suite 490', 'New Dorothyborough', 'NM', 'USA', '66571');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Antonio', 'Brooks', '(628)067-8882', '4504 Joseph Pines Apt. 323', 'Pittmanhaven', 'CT', 'USA', '20743');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Daniel', 'Phillips', '001-493-699-2304x52704', '7549 Frank View', 'Port Anita', 'IL', 'USA', '42673');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Daniel', 'Clark', '442-011-5586', '2341 Smith Loaf', 'Stewartfurt', 'AK', 'USA', '18464');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Scott', 'Hudson', '(202)710-4010x355', '087 Pamela Lake', 'North Douglastown', 'NV', 'USA', '01149');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Frederick', 'Obrien', '001-879-237-4854x883', '057 Juan Branch Apt. 372', 'Port Zachary', 'VA', 'USA', '01056');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Debbie', 'Stein', '+1-268-788-4232', '238 George Views', 'North Michaelside', 'ME', 'USA', '69471');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Michael', 'Rogers', '(958)241-9173x148', '83066 Campbell Corner Suite 603', 'Scottton', 'MT', 'USA', '17402');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('David', 'Wolfe', '662.206.6223x74983', '110 Stephenson Mews', 'Jackside', 'NH', 'USA', '67460');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Amanda', 'Weaver', '547.405.8574x35379', '4526 Richard Mission Suite 089', 'Brookestad', 'KS', 'USA', '24103');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Nichole', 'Frazier', '132.201.1037x607', '9634 Rodriguez Radial Apt. 186', 'Melissaside', 'AL', 'USA', '67584');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Angela', 'Robbins', '371-348-6643x1519', '31496 Sheri Squares', 'Nielsentown', 'IL', 'USA', '66561');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Meghan', 'Bailey', '209-101-0534x9266', '10110 Moss Field', 'Hayleyfurt', 'NY', 'USA', '94923');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jennifer', 'Wilson', '6127422011', '18100 Kathleen Canyon Suite 728', 'Robinsonberg', 'DC', 'USA', '45568');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('David', 'Yu', '6120909799', '6862 Ferguson Stream', 'Elizabethburgh', 'NV', 'USA', '66392');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Ronald', 'Moore', '7334770165', '8215 Ian Crescent', 'Lake Brianafurt', 'NM', 'USA', '16306');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Marvin', 'Russell', '577.931.6458', '330 Robert Oval', 'Jacksonburgh', 'AL', 'USA', '21169');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Wendy', 'Campos', '+1-821-878-4053', '4014 Zavala Underpass Apt. 845', 'Gibsonborough', 'DE', 'USA', '53633');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Jesus', 'Acosta', '9192979297', '832 Smith Union Apt. 179', 'South Joshuashire', 'HI', 'USA', '85555');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Robin', 'Kelly', '(984)112-0321x7817', '496 Bennett Manor Suite 538', 'North Michele', 'ND', 'USA', '77538');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Robert', 'Frank', '+1-927-879-4886x486', '8118 Kathy Orchard', 'South Ericafort', 'MT', 'USA', '94125');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Ann', 'Wang', '(369)280-4897x0341', '95312 Joshua Lake', 'Coletown', 'OR', 'USA', '27701');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Victoria', 'Cochran', '001-375-674-3221x434', '6584 Taylor Fork', 'Lake Julieland', 'OH', 'USA', '51034');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Kayla', 'Graves', '351-253-6270x4135', '571 Jason Key Suite 719', 'North Cheryl', 'NE', 'USA', '47361');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Penny', 'Cabrera', '1159313790', '98373 Brown Summit Suite 065', 'South Deannaland', 'WY', 'USA', '35314');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Susan', 'Miller', '619-104-6245', '42363 Clark Place', 'Michaelmouth', 'WA', 'USA', '69961');
INSERT INTO mydb.Customer (firstName, lastName, Phone, Address, City, State, Country, PostalCode) VALUES ('Angela', 'Thomas', '+1-408-129-1001x52294', '29477 Jones Pass Suite 321', 'South Brandon', 'NC', 'USA', '95696');

-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Order_Customer_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO mydb.Order (date, CustomerID) VALUES ('2024-10-07 05:20:56', 44);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2024-03-25 16:49:20', 38);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2020-06-24 09:11:04', 75);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2021-12-11 17:31:51', 56);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2021-10-10 02:23:55', 71);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2021-04-18 11:21:28', 22);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2020-07-19 21:39:31', 64);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2024-07-04 07:14:06', 91);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2022-10-02 12:19:09', 52);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2023-04-29 10:47:25', 91);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2022-11-05 01:45:11', 56);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2020-09-18 15:24:17', 16);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2023-12-23 23:05:32', 43);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2023-10-30 23:19:00', 49);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2024-03-20 20:27:01', 38);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2021-12-23 12:24:09', 39);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2023-08-04 19:14:37', 38);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2023-11-12 17:38:37', 81);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2020-10-10 18:06:08', 61);
INSERT INTO mydb.Order (date, CustomerID) VALUES ('2021-08-09 20:39:03', 58);


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `InventoryID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  `Price` FLOAT NOT NULL,
  `QuantStock` INT NOT NULL,
  `dateStocked` DATETIME NULL,
  PRIMARY KEY (`InventoryID`))
ENGINE = InnoDB;


INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Magical Tree', 203.63, 2, '2023-06-24 01:02:44');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Magic Seed', 233.67, 97, '2023-07-07 06:44:56');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Beanstalk', 733.17, 31, '2022-10-24 13:02:43');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Beanstalk Seed', 632.19, 97, '2020-09-01 19:04:36');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Fur Tree', 130.67, 56, '2022-06-23 12:42:20');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Fur Seed', 902.1, 52, '2023-12-08 03:59:47');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Spruce Tree', 326.0, 44, '2020-01-25 12:11:36');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Spruce Seed', 972.62, 34, '2021-05-07 02:40:37');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Coconut Tree', 558.22, 92, '2023-11-20 01:51:49');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Cocunuts', 561.03, 9, '2021-01-10 22:34:08');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Apple Tree', 920.85, 12, '2022-06-25 20:51:46');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Apple Seed', 164.52, 75, '2022-09-27 16:35:57');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Orange Tree', 522.24, 62, '2020-10-22 16:11:02');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Orange Seed', 409.36, 81, '2022-10-26 20:53:39');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Pear Tree', 767.73, 41, '2022-07-11 21:19:13');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Pear Seed', 147.2, 53, '2023-10-17 12:35:09');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Alpine Tree', 57.33, 6, '2020-02-08 05:13:30');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Alpine Seed', 502.81, 11, '2021-07-14 20:53:16');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Druid Tree', 820.4, 79, '2022-12-10 01:30:34');
INSERT INTO mydb.Inventory (Description, Price, QuantStock, dateStocked) VALUES ('Druid Seed', 484.47, 5, '2024-09-14 10:51:33');


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `SupplierID` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;

INSERT INTO mydb.Supplier (CompanyName) VALUES ('Porter Inc');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Sanchez-Price');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Richard, Phillips and King');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Kline, Underwood and Collier');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Miller-Williams');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Mitchell-Fox');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Garcia-Martin');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Golden Ltd');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Brown, Miller and Green');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('Norton, Becker and Rocha');
INSERT INTO mydb.Supplier (CompanyName) VALUES ('THE MOST USELESS SUPPLIER CO');


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_and_Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventory_and_Suppliers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_and_Suppliers` (
  `SupplierID` INT NOT NULL,
  `InventoryID` INT NOT NULL,
  PRIMARY KEY (`SupplierID`, `InventoryID`),
  INDEX `fk_Supplier_has_Inventory_Inventory1_idx` (`InventoryID` ASC) VISIBLE,
  INDEX `fk_Supplier_has_Inventory_Supplier1_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_has_Inventory_Supplier1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `mydb`.`Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_has_Inventory_Inventory1`
    FOREIGN KEY (`InventoryID`)
    REFERENCES `mydb`.`Inventory` (`InventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Inserting into Inventory_and_Suppliers
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (1, 1);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (2, 2);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (3, 3);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (4, 4);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (5, 5);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (6, 6);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (7, 7);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (8, 8);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (9, 9);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (10, 10);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (1, 11);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (2, 12);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (3, 13);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (4, 14);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (5, 15);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (6, 16);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (7, 17);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (8, 18);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (9, 19);
INSERT INTO `mydb`.`Inventory_and_Suppliers` (`SupplierID`, `InventoryID`) VALUES (10, 20);
-- Continue pattern for 100 rows
-- ...
-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_has_Inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Inventory` (
  `OrderID` INT NOT NULL,
  `InventoryID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`OrderID`, `InventoryID`),
  INDEX `fk_Order_has_Inventory_Inventory1_idx` (`InventoryID` ASC) VISIBLE,
  INDEX `fk_Order_has_Inventory_Order1_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Inventory_Order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Inventory_Inventory1`
    FOREIGN KEY (`InventoryID`)
    REFERENCES `mydb`.`Inventory` (`InventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Inserting into Order_has_Inventory
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (1, 1, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (1, 2, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (2, 2, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (2, 12, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (2, 3, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (3, 33, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (4, 12, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (4, 15, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (5, 6, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (1, 3, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (2, 4, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (2, 5, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (2, 6, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (3, 7, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (3, 8, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (4, 9, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (4, 10, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (5, 11, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (5, 12, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (6, 13, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (6, 14, 9);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (7, 15, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (8, 16, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (9, 17, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (9, 18, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (10, 19, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (11, 1, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (11, 3, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (12, 4, 10);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (12, 5, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (13, 6, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (13, 7, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (14, 8, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (14, 9, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (15, 10, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (15, 11, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (16, 12, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (16, 13, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (17, 14, 2);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (17, 15, 9);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (18, 16, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (18, 17, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (19, 18, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (19, 19, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (18, 1, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (15, 9, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (17, 7, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (11, 10, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (19, 4, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (16, 3, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (10, 2, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (12, 13, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (19, 15, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (16, 11, 7);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (18, 14, 9);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (14, 16, 5);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (17, 12, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (13, 17, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (15, 18, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (11, 19, 6);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (20, 12, 3);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (20, 17, 8);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (20, 18, 4);
INSERT INTO `mydb`.`Order_has_Inventory` (`OrderID`, `InventoryID`, `Quantity`) VALUES (20, 19, 6);

-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `ContactID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `SupplierID` INT NOT NULL,
  PRIMARY KEY (`ContactID`),
  INDEX `fk_Contact_Supplier1_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_Supplier1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `mydb`.`Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Christian', 'Smith', '(816)520-2848', 'xwilson@gonzalez.info', 1);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Mitchell', 'Rowe', '(443)460-0059x338', 'wilsonjohn@fisher.net', 1);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Manuel', 'Thomas', '001-231-104-8449x161', 'jason78@jackson.com', 2);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Jessica', 'Ruiz', '+1-269-181-3991x864', 'crystal65@yahoo.com', 2);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Michele', 'Oliver', '(615)514-4729x8584', 'kirsten06@flores.com', 3);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Peter', 'Thomas', '264-093-5827x4927', 'cynthia41@hotmail.com', 3);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Cheryl', 'Fisher', '(270)079-9825', 'michaelwright@taylor.com', 4);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Deborah', 'Hooper', '2595772083', 'kristengarcia@gmail.com', 4);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Stephanie', 'Ford', '5109268970', 'eileen14@gmail.com', 5);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Michelle', 'Miller', '313-779-5483x2069', 'njohnson@jones.info', 5);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Richard', 'Warren', '001-131-010-9957x856', 'tonya47@kent.com', 6);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Maxwell', 'Mosley', '(116)971-0016x23922', 'michellesmith@taylor-garza.net', 6);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Linda', 'Johnson', '284.247.2020', 'wrightmichelle@craig.com', 7);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Stephen', 'Solis', '+1-709-714-5699x5215', 'johnsonwayne@yahoo.com', 7);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Darin', 'Mendez', '001-281-368-6725x78843', 'allisonmartinez@green-castaneda.com', 8);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Andrew', 'Moran', '001-262-776-3386x4175', 'dkelley@hotmail.com', 8);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Jennifer', 'Gay', '623.518.3953x146', 'pcain@hotmail.com', 9);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('John', 'Torres', '664.877.9020', 'jeffrey27@ford-boyd.com', 9);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Kimberly', 'Martin', '815.620.6356x0625', 'mackenzie78@yahoo.com', 10);
INSERT INTO Contact (firstName, lastName, Phone, email, SupplierID) VALUES ('Bryan', 'Burns', '+1-434-658-2886x35023', 'joshuamartinez@odom-hebert.com', 10);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
