-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 07:40:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `Phone` VARCHAR(13) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(2) NULL,
  `Country` VARCHAR(45) NULL,
  `Postal Code` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `OrderID` INT NOT NULL,
  `Date` DATETIME NULL,
  `CustomerID` INT NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Order_Customer_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `InventoryID` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Price` FLOAT NOT NULL,
  `QuantStock` INT NOT NULL,
  `dateStocked` DATETIME NULL,
  PRIMARY KEY (`InventoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `SupplierID` INT NOT NULL,
  `CompanyName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory_and_Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventory_and_Suppliers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventory_and_Suppliers` (
  `SupplierID` INT NOT NULL,
  `InventoryID` INT NOT NULL,
  PRIMARY KEY (`SupplierID`, `InventoryID`),
  INDEX `fk_Supplier_has_Inventory_Inventory1_idx` (`InventoryID` ASC) VISIBLE,
  INDEX `fk_Supplier_has_Inventory_Supplier1_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_has_Inventory_Supplier1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `mydb`.`Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_has_Inventory_Inventory1`
    FOREIGN KEY (`InventoryID`)
    REFERENCES `mydb`.`Inventory` (`InventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_has_Inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_has_Inventory` (
  `OrderID` INT NOT NULL,
  `InventoryID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`OrderID`, `InventoryID`),
  INDEX `fk_Order_has_Inventory_Inventory1_idx` (`InventoryID` ASC) VISIBLE,
  INDEX `fk_Order_has_Inventory_Order1_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Inventory_Order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Inventory_Inventory1`
    FOREIGN KEY (`InventoryID`)
    REFERENCES `mydb`.`Inventory` (`InventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contact` (
  `ContactID` INT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `SupplierID` INT NOT NULL,
  PRIMARY KEY (`ContactID`),
  INDEX `fk_Contact_Supplier1_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_Supplier1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `mydb`.`Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
